services:
  auth:
    build:
      context: auth
      dockerfile: ./Dockerfile
    ports:
      - 8081:8081
    healthcheck:
      interval: 2s
      timeout: 1s 
      start_period: 0s 
      retries: 10 
      test: node healthcheck.js
  places:
    build:
      context: places
      dockerfile: ./Dockerfile
    ports:
      - 8082:8082
    healthcheck:
      interval: 2s
      timeout: 1s 
      start_period: 0s 
      retries: 10 
      test: node healthcheck.js
  profile:
    build:
      context: profile
      dockerfile: ./Dockerfile
    ports:
      - 8083:8083
    healthcheck:
      interval: 2s
      timeout: 1s 
      start_period: 0s 
      retries: 10 
      test: node healthcheck.js
  host:
    build:
      context: host
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    healthcheck:
      interval: 2s
      timeout: 1s 
      start_period: 15s 
      retries: 10
      test: node healthcheck.js
    depends_on:
      auth:
        condition: service_healthy
      places:
        condition: service_healthy
      profile:
        condition: service_healthy